name = "Unrolled"
uuid = "9602ed7d-8fef-5bc8-8597-8f21381861e8"
version = "0.1.4"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.5"
julia = "0.7, 1.0"

[extras]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
QuickTypes = "ae2dfa86-617c-530c-b392-ef20fdad97bb"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["StaticArrays", "Test", "QuickTypes", "MacroTools"]
